module Exams.BobTaitChapterRevisionBAP(
  bob_tait_chapter_revision_BAP
, bob_tait_chapter_revision_BAP_test01
, bob_tait_chapter_revision_BAP_test02
, bob_tait_chapter_revision_BAP_test03
, bob_tait_chapter_revision_BAP_test04
, bob_tait_chapter_revision_BAP_test05
) where

import Control.Lens(( # ))
import Document.AST
import Document.AviationExamMeta
import Document.ExamAST
import Data.Functor((<$>))
import Data.Maybe(Maybe(Nothing))
import Data.String(String)

bob_tait_chapter_revision_BAP ::
  Exam TestMeta (ExamMeta String) (Blocks String)
bob_tait_chapter_revision_BAP =
  Exam
    (examMetaTitle "Bob Tait RPL Study Guide Chapter Revision BAP")
    (Tests
      [
        bob_tait_chapter_revision_BAP_test01
      , bob_tait_chapter_revision_BAP_test02
      , bob_tait_chapter_revision_BAP_test03
      , bob_tait_chapter_revision_BAP_test04
      , bob_tait_chapter_revision_BAP_test05
      ]
    )

bob_tait_chapter_revision_BAP_test01 ::
  Test TestMeta (Blocks String)
bob_tait_chapter_revision_BAP_test01 =
  str <$>
    Test
    ("An aircraft with this loading system has 200lbs on the rear seats. The moment index generated by this weight would be closest to")
    (_Multichoice # (MultichoiceAnswer
      [
        "30"
      ]

      "25.2"

      [
        "12.5"
      , "33"
      ]))
    Nothing
    (bobtait_meta ..~ rpl_meta ..~ notestmeta)

bob_tait_chapter_revision_BAP_test02 ::
  Test TestMeta (Blocks String)
bob_tait_chapter_revision_BAP_test02 =
  str <$>
    Test
    ("The combined weight of the pilot and front passenger in an aircraft with this loading system is 340lbs. The moment index generated by this weight would be closest to")
    (_Multichoice # (MultichoiceAnswer
      [
        "3"
      , "309"
      , "134"
      ]

      "31"

      [
        
      ]))
    Nothing
    (bobtait_meta ..~ rpl_meta ..~ notestmeta)

bob_tait_chapter_revision_BAP_test03 ::
  Test TestMeta (Blocks String)
bob_tait_chapter_revision_BAP_test03 =
  str <$>
    Test
    ("An aircraft which uses this loading system is loaded as follows. Basic empty weight, 1240lb, 100.80 moment index. Row 1, Pilot and passenger 339lbs. Row 2, empty. Baggage, 50lbs. Fuel at take-off 37 US gal.")
    (_Multichoice # (MultichoiceAnswer
      [
        
      ]

      "This aircraft WILL remain within balance limits at all stages of the flight"

      [
        "This aircraft WILL NOT remain within balance limits at all stages of the flight"
      ]))
    Nothing
    (bobtait_meta ..~ rpl_meta ..~ notestmeta)

bob_tait_chapter_revision_BAP_test04 ::
  Test TestMeta (Blocks String)
bob_tait_chapter_revision_BAP_test04 =
  str <$>
    Test
    ("An aircraft with this loading system is loaded so that its gross weight is 1950lbs and the total moment index is 170 index units. The position of the centre of gravity with this load configuration in inches aft of the datum is closest to")
    (_Multichoice # (MultichoiceAnswer
      [
        
      ]

      "87 inches aft of the datum"

      [
        "67 inches aft of the datum"
      , "101 inches aft of the datum"
      , "120 inches aft of the datum"
      ]))
    Nothing
    (bobtait_meta ..~ rpl_meta ..~ notestmeta)

bob_tait_chapter_revision_BAP_test05 ::
  Test TestMeta (Blocks String)
bob_tait_chapter_revision_BAP_test05 =
  str <$>
    Test
    ("An aircraft with this loading system has been loaded so that its take-off totals are as follows. Gross Weight=2100lbs. Total moment index 196. If the baggage compartment is full, what is the minimum weight which must be removed to ensure that the aircraft is within balance limits for take-off?")
    (_Multichoice # (MultichoiceAnswer
      [
        "none"
      ]

      "25lbs"

      [
        "50lbs"
      , "100lbs"
      ]))
    Nothing
    (bobtait_meta ..~ rpl_meta ..~ notestmeta)
